# Generated by Django 3.1.3 on 2021-01-10 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Geo_Type', models.CharField(max_length=20)),
                ('Memo', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_N101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Geo_Type', models.CharField(max_length=20)),
                ('Memo', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_N103',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Geo_Type', models.CharField(max_length=20)),
                ('Memo', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_N106',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Geo_Type', models.CharField(max_length=20)),
                ('Memo', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_N109',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Geo_Type', models.CharField(max_length=20)),
                ('Memo', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_T316',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Geo_Type', models.CharField(max_length=20)),
                ('Memo', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Panel_name', models.CharField(max_length=255)),
                ('Operator_name', models.CharField(max_length=255)),
                ('Depth', models.CharField(max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='category ', max_length=255)),
                ('Site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
