# Generated by Django 3.1.2 on 2020-11-18 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Panel_name', models.CharField(max_length=255)),
                ('Operator_name', models.CharField(max_length=255)),
                ('Bite_name', models.CharField(max_length=255)),
                ('Detail_name', models.CharField(max_length=255)),
                ('Depth', models.CharField(max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='category ', max_length=255)),
                ('Site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
