# Generated by Django 3.1.2 on 2020-11-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Panel_name_tag',
            field=models.CharField(default='Current Excavation panels details...', max_length=255),
        ),
    ]
