# Generated by Django 3.1.2 on 2020-11-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_panel_name_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Panel_name_tag',
        ),
    ]
