# Generated by Django 3.1.3 on 2020-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201128_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_N101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=10)),
                ('Operator', models.CharField(max_length=10)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Memo', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
