# Generated by Django 3.1.3 on 2021-01-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='Operator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='Site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n101',
            name='Operator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n101',
            name='Site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n103',
            name='Operator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n103',
            name='Site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n106',
            name='Operator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n106',
            name='Site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n109',
            name='Operator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_n109',
            name='Site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_t316',
            name='Operator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board_t316',
            name='Site',
            field=models.CharField(max_length=20),
        ),
    ]
