# Generated by Django 3.1.2 on 2020-11-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_post_panel_name_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Site_name',
        ),
    ]
