# Generated by Django 3.1.3 on 2021-01-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210111_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='Memo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n101',
            name='Memo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n103',
            name='Memo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n106',
            name='Memo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n109',
            name='Memo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_t316',
            name='Memo',
            field=models.CharField(max_length=50),
        ),
    ]
