# Generated by Django 3.1.3 on 2020-12-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
