# Generated by Django 3.1.3 on 2021-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_n101',
            name='Geo_Type',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
