# Generated by Django 3.1.2 on 2020-11-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201104_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='Site_selection',
        ),
    ]
