# Generated by Django 3.2.4 on 2021-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210115_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Labrador_BC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(max_length=20)),
                ('Operator', models.CharField(max_length=50)),
                ('Panel_No', models.CharField(max_length=20)),
                ('Activity', models.CharField(max_length=40)),
                ('Bite', models.CharField(max_length=20)),
                ('Depth', models.CharField(max_length=20)),
                ('Geo_Type', models.CharField(max_length=20)),
                ('Tooth_Qty', models.CharField(max_length=40)),
                ('Memo', models.CharField(max_length=70)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='Activity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board',
            name='Operator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='Tooth_Qty',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n101',
            name='Activity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n101',
            name='Operator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n101',
            name='Tooth_Qty',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n103',
            name='Activity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n103',
            name='Operator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n103',
            name='Tooth_Qty',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n106',
            name='Activity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n106',
            name='Operator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n106',
            name='Tooth_Qty',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n109',
            name='Activity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_n109',
            name='Operator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_n109',
            name='Tooth_Qty',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_t316',
            name='Activity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='board_t316',
            name='Operator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board_t316',
            name='Tooth_Qty',
            field=models.CharField(max_length=40),
        ),
    ]
