# Generated by Django 3.1.2 on 2020-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201104_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Site_selection',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='category ', max_length=255),
        ),
    ]
