# Generated by Django 3.1.3 on 2021-01-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_board_n101_geo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='Geo_Type',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_n103',
            name='Geo_Type',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_n106',
            name='Geo_Type',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_n109',
            name='Geo_Type',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
